[package]
name = "dunes"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.21.3"
proc-bitfield = "0.2.2"

[dev-dependencies]
bincode = "2.0.0-rc.3"

[profile.test]
# The tests are too slow without some optimizations.
opt-level = 2
