[workspace]
resolver = "2"
members = [
    "backend",
    "frontend",
]

# Compile dependencies with full optimizations in develop.
[profile.dev.package."*"]
opt-level = 3

# Compile with some optimizations in develop. The tests run much faster with
# them.
[profile.dev]
opt-level = 1
