[package]
name = "dunes"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.21.3"
proc-bitfield = "0.2.2"

[dev-dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[profile.test]
# The tests are too slow without some optimizations.
opt-level = 2
