name: CI

on:
  push:
    branches:
      - main

env:
  RUSTFLAGS: -D warnings

# TODO: Run check and test on the whole workspace.
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo check -p backend

  test:
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob download --account-name dunesroms --container-name roms --name roms.tar.gz --file roms.tar.gz --auth-mode login
      - run: tar -xzvf roms.tar.gz
      - run: cargo test -p backend
